/*
Copyright 2024 The Alibaba Cloud Karpenter Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package bootstrap

import (
	"bytes"
	"fmt"
	"text/template"
)

// KubeadmBootstrapper generates bootstrap scripts for self-managed Kubernetes clusters using kubeadm
type KubeadmBootstrapper struct{}

// NewKubeadmBootstrapper creates a new kubeadm bootstrapper
func NewKubeadmBootstrapper() *KubeadmBootstrapper {
	return &KubeadmBootstrapper{}
}

// GenerateUserData generates the user data script for kubeadm cluster
func (b *KubeadmBootstrapper) GenerateUserData(opts BootstrapOptions) (string, error) {
	tmpl, err := template.New("kubeadm-userdata").Parse(kubeadmUserDataTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse kubeadm template: %w", err)
	}

	// Format labels and taints
	labels := formatLabels(opts.Labels)
	taints := formatTaints(opts.Taints)

	// Get maxPods from kubelet config if available
	var maxPods *int32
	if opts.KubeletConfig != nil {
		maxPods = opts.KubeletConfig.MaxPods
	}

	data := map[string]interface{}{
		"ClusterEndpoint":  opts.ClusterEndpoint,
		"NodeName":         opts.NodeName,
		"Labels":           labels,
		"Taints":           taints,
		"MaxPods":          maxPods,
		"CustomUserData":   opts.CustomUserData,
		"ContainerRuntime": opts.ContainerRuntime,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute kubeadm template: %w", err)
	}

	return buf.String(), nil
}

const kubeadmUserDataTemplate = `#!/bin/bash
set -euo pipefail

# Kubeadm Node Bootstrap Script
# Generated by Karpenter Alibaba Cloud Provider

NODE_NAME="{{.NodeName}}"
CLUSTER_ENDPOINT="{{.ClusterEndpoint}}"
CONTAINER_RUNTIME="{{.ContainerRuntime}}"
LOG_FILE="/var/log/karpenter-bootstrap.log"

# Logging function
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a ${LOG_FILE}
}

log "Starting Kubeadm node bootstrap"

# 1. Set hostname
log "Setting hostname to ${NODE_NAME}"
hostnamectl set-hostname ${NODE_NAME}

# 2. Disable swap (required by Kubernetes)
log "Disabling swap"
swapoff -a
sed -i '/swap/d' /etc/fstab

# 3. Load required kernel modules
log "Loading required kernel modules"
cat > /etc/modules-load.d/k8s.conf <<EOF
overlay
br_netfilter
EOF

modprobe overlay
modprobe br_netfilter

# 4. Configure sysctl for Kubernetes
log "Configuring sysctl parameters"
cat > /etc/sysctl.d/k8s.conf <<EOF
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

sysctl --system

# 5. Install container runtime
log "Installing container runtime: ${CONTAINER_RUNTIME}"

if [ "${CONTAINER_RUNTIME}" = "containerd" ] || [ "${CONTAINER_RUNTIME}" = "" ]; then
    log "Installing containerd"
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    yum install -y containerd.io

    # Configure containerd
    mkdir -p /etc/containerd
    containerd config default > /etc/containerd/config.toml

    # Enable systemd cgroup driver
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

    # Configure Alibaba Cloud mirror for better performance in China regions
    sed -i 's|registry.k8s.io|registry.aliyuncs.com/google_containers|g' /etc/containerd/config.toml

    systemctl enable containerd
    systemctl restart containerd
    log "Containerd installed and configured"
    
elif [ "${CONTAINER_RUNTIME}" = "docker" ]; then
    log "Installing Docker (legacy support)"
    yum install -y yum-utils device-mapper-persistent-data lvm2
    yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
    yum install -y docker-ce docker-ce-cli
    
    # Configure Docker daemon
    mkdir -p /etc/docker
    cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2",
  "registry-mirrors": ["https://registry.aliyuncs.com"]
}
EOF
    
    systemctl enable docker
    systemctl restart docker
    log "Docker installed and configured"
else
    log "ERROR: Unsupported container runtime: ${CONTAINER_RUNTIME}"
    exit 1
fi

# 6. Install kubeadm, kubelet, kubectl
log "Installing Kubernetes components"
cat > /etc/yum.repos.d/kubernetes.repo <<EOF
[kubernetes]
name=Kubernetes
baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
EOF

yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes 2>&1 | tee -a ${LOG_FILE}
systemctl enable kubelet
log "Kubernetes components installed"

# 7. Configure kubelet
log "Configuring kubelet"
cat > /etc/sysconfig/kubelet <<EOF
KUBELET_EXTRA_ARGS="--node-ip=\$(hostname -I | awk '{print \$1}'){{if .Labels}} --node-labels={{.Labels}}{{end}}{{if .Taints}} --register-with-taints={{.Taints}}{{end}}{{if .MaxPods}} --max-pods={{.MaxPods}}{{end}}{{if .ClusterDNS}} --cluster-dns={{.ClusterDNS}}{{end}}{{if .PodSubnet}} --pod-cidr={{.PodSubnet}}{{end}}"
EOF

# 8. Create kubeadm join configuration
log "Creating kubeadm join configuration"
cat > /tmp/kubeadm-join-config.yaml <<EOF
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
nodeRegistration:
  name: ${NODE_NAME}
  kubeletExtraArgs:
    node-ip: \$(hostname -I | awk '{print \$1}'){{if .MaxPods}}
    max-pods: "{{.MaxPods}}"{{end}}{{if .ClusterDNS}}
    cluster-dns: "{{.ClusterDNS}}"{{end}}
  taints: []
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{.ClusterEndpoint}}"
    token: "{{.JoinToken}}"
    caCertHashes:
      - "{{.CACertHash}}"
    # Increase timeout for token validation
    timeout: 5m0s
EOF

# 9. Join the cluster with retry logic
log "Joining cluster at ${CLUSTER_ENDPOINT}"
JOIN_MAX_RETRIES=3
JOIN_RETRY_DELAY=10
JOIN_RETRY_COUNT=0

while [ ${JOIN_RETRY_COUNT} -lt ${JOIN_MAX_RETRIES} ]; do
    if kubeadm join --config /tmp/kubeadm-join-config.yaml 2>&1 | tee -a ${LOG_FILE}; then
        log "Successfully joined the cluster"
        break
    fi
    
    JOIN_RETRY_COUNT=$((JOIN_RETRY_COUNT + 1))
    if [ ${JOIN_RETRY_COUNT} -lt ${JOIN_MAX_RETRIES} ]; then
        log "Join failed (attempt ${JOIN_RETRY_COUNT}/${JOIN_MAX_RETRIES}), retrying in ${JOIN_RETRY_DELAY}s..."
        sleep ${JOIN_RETRY_DELAY}
    else
        log "ERROR: Failed to join cluster after ${JOIN_MAX_RETRIES} attempts"
        exit 1
    fi
done

# 10. Verify node joined
log "Waiting for node to be ready..."
REGISTER_TIMEOUT=300
ELAPSED=0
while [ ${ELAPSED} -lt ${REGISTER_TIMEOUT} ]; do
    if kubectl --kubeconfig=/etc/kubernetes/kubelet.conf get node ${NODE_NAME} &>/dev/null; then
        log "Node ${NODE_NAME} successfully registered"
        break
    fi
    sleep 5
    ELAPSED=$((ELAPSED + 5))
    if [ $((ELAPSED % 30)) -eq 0 ]; then
        log "Still waiting for node registration... (${ELAPSED}s elapsed)"
    fi
done

if [ ${ELAPSED} -ge ${REGISTER_TIMEOUT} ]; then
    log "WARNING: Node registration timed out after ${REGISTER_TIMEOUT}s"
fi

# 11. Apply labels and taints if needed
{{if .Labels}}
log "Applying node labels"
kubectl --kubeconfig=/etc/kubernetes/kubelet.conf label node ${NODE_NAME} {{.Labels}} --overwrite 2>&1 | tee -a ${LOG_FILE}
{{end}}

{{if .Taints}}
log "Applying node taints"
kubectl --kubeconfig=/etc/kubernetes/kubelet.conf taint node ${NODE_NAME} {{.Taints}} --overwrite 2>&1 | tee -a ${LOG_FILE}
{{end}}

log "Node ${NODE_NAME} successfully joined the cluster!"

{{if .CustomUserData}}
# 12. Execute custom user data
log "Executing custom user data..."
{{.CustomUserData}} 2>&1 | tee -a ${LOG_FILE}
{{end}}

log "Bootstrap completed successfully!"
echo "Bootstrap completed at $(date)" > /var/lib/karpenter/bootstrap-complete
`
