name: E2EVersionCompatibilityTrigger
on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        default: cn-hangzhou
      cleanup:
        type: boolean
        default: true
permissions:
  contents: read
concurrency:
  group: e2e-version-compatibility-${{ github.ref }}
  cancel-in-progress: false
jobs:
  version-compatibility:
    strategy:
      fail-fast: false
      matrix:
        k8s_version:
          - "1.30"
          - "1.31"
          - "1.32"
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Integration
      region: ${{ inputs.region }}
      k8s_version: ${{ matrix.k8s_version }}
      cleanup: ${{ inputs.cleanup }}
      workflow_trigger: versionCompatibility
      source: alibabacloud
    secrets:
      ALIBABA_CLOUD_E2E_CONFIG: ${{ secrets.ALIBABA_CLOUD_E2E_CONFIG }}
      ALIBABA_CLOUD_ACCESS_KEY_ID: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
      ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
