name: E2ESoakTrigger
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch: {}
permissions:
  contents: read
concurrency:
  group: e2e-soak-${{ github.ref }}
  cancel-in-progress: false
jobs:
  soak:
    uses: ./.github/workflows/e2e.yaml
    with:
      suite: Integration
      region: cn-hangzhou
      workflow_trigger: soak
      cleanup: true
      source: alibabacloud
    secrets:
      ALIBABA_CLOUD_E2E_CONFIG: ${{ secrets.ALIBABA_CLOUD_E2E_CONFIG }}
      ALIBABA_CLOUD_ACCESS_KEY_ID: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
      ALIBABA_CLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
